# Generated by Django 3.1.8 on 2021-07-01 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210630_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderpositions',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
    ]
